name: Deploy
description: Deploy image to Google Cloud Run

inputs:
  service-account:
    description: Service account
    required: true
  app-env:
    description: App environment
    required: true
  project-id:
    description: Project ID
    required: true
  image-name:
    description: Image name
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.service-account }}
        project_id: ${{ inputs.project-id }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloudrun
      shell: bash
      run: |-
          gcloud run deploy ${{ inputs.project-id }}-${{ inputs.app-env }} \
            --region europe-west2 \
            --europe-west2-docker.pkg.dev/${{ inputs.project-id }}/server/${{ inputs.image-name }}:latest \
            --set-env-vars "PORT=8000" \
            --port "8080" \
            --platform "managed" \
            --allow-unauthenticated \