---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ master ]

env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: crowdfund-web3
  IMAGE_NAME: server

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Deploy - Production
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to GCP
        uses: ./.github/actions/build
        with:
          service-account: ${{ env.SERVICE_ACCOUNT }}
          project-id: ${{ PROJECT_ID }}
          image-name: ${{ IMAGE_NAME }}