---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ master ]

env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: crowdfund-web3
  IMAGE_NAME: server
  GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Deploy - Production
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to GCP
        uses: ./.github/actions/build
        with:
          service-account: ${{ env.SERVICE_ACCOUNT_KEY }}
          project-id: ${{ env.PROJECT_ID }}
          image-name: ${{ env.IMAGE_NAME }}
          git-tag: ${{ env.GIT_TAG }}